global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#prometheus'
        send_resolved: true

