global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerting_rules.yml


scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['18.234.35.25:3000', '18.234.35.25:9093', '18.234.35.25:9090']
 
